moviepro/app4/urls.py
from  . import views
from django.urls import path

app_name='app4'
urlpatterns = [
     path('',views.demo,name='demo'),
     path('movie/<int:movie_id>/',views.detail,name='detail'),
     path('add/',views.add_movie,name='add_movie'),
     path('update/<int:id>/',views.update,name='update'),
     path('delete/<int:id>/',views.delete,name='delete')

]

moviepro/moviepro/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app4.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

moviepro/app4/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    name=models.CharField(max_length=250)
    desc=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='pic')

    def __str__(self):
        return self.name

moviepro/app4/forms.py
from django import forms
from .models import Movie

class MovieForm(forms.ModelForm):
    class Meta:
        model=Movie
        fields=['name','desc','year','img']

moviepro/app4/views.py
from django.shortcuts import render, HttpResponse, redirect
from .models import Movie
from .forms import MovieForm
# Create your views here.
def demo(request):
    movie=Movie.objects.all()
    context={
        'movie_list':movie
    }
    return render(request,'index.html',context)
def detail(request,movie_id):
    movie=Movie.objects.get(id=movie_id)
    return render(request,"detail.html",{'asd':movie})

def add_movie(request):
    if request.method=="POST":
        name = request.POST.get('name')
        desc = request.POST.get('desc')
        year = request.POST.get('year')
        img = request.FILES['img']

        movie=Movie(name=name,desc=desc,year=year,img=img)
        movie.save()
        return redirect('/')
    return render(request,'add.html')

def update(request,id):
    abc=Movie.objects.get(id=id)
    form=MovieForm(request.POST or None, request.FILES,instance=abc)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'qwe':form,'asd':abc})

def delete(request,id):
    if request.method=='POST':
        movie=Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request,'delete.html')

moviepro/templates/add.html
{% extends 'base.html' %}
{% block body %}

<form method="POST" enctype="multipart/form-data">
    {%csrf_token %}
    <input type="text" name="name" placeholder="Enter movie name"><br><br>
    <input type="text" name="desc" placeholder="Enter the movie description"><br><br>
    <input type="text" name="year" placeholder="Enter movie year"><br><br>
    <input type="file" name="img" ><br><br>
    <input type="submit">
</form>
{% endblock %}

moviepro/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
    Online Movie Store
  </a>
    <a href="{% url 'app4:add_movie' %}"><button type="button">Add Movie </button></a>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

moviepro/templates/delete.html
<form method="POST">

  {% csrf_token %}

  Are you want to delete this movie?
  <input type="submit">
</form>

moviepro/templates/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{asd.img.url}}" width="350" height="350">

        </div>

<div class="col-md-6">
    <h4>{{asd.name}}<br></h4>
    <h6>{{asd.desc}}</h6>
    <h6>{{asd.year}}</h6>

    <a class="btn btn-warning" href="{% url 'app4:update' asd.id %}">Update</a>
  <a class="btn btn-danger" href="{% url 'app4:delete' asd.id %}">Delete</a><br>
</div>
    </div>

</div>

{% endblock %}

moviepro/templates/edit.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{qwe.as_p}}
    <input type="submit">
</form>

moviepro/templates/index.html
{% extends 'base.html' %}
{% block body %}

<div class="container">
    <div class="row mx_auto">
        {% for i in movie_list %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4 xol-lg-4">
            <div class="card text-center asd" style="min-width:18rem;" >
  <img class="card-img-top" src="{{i.img.url}}" alt=""  height="200px" width="200px">
  <div class="card">
    <h5 class="title">{{i.name}}</h5>
    <p class="text "> {{i.desc}}</p>
    <a href="{% url 'app4:detail' i.id%}" class=" qwe">View details</a>
  </div>
</div>
        </div>
        {% endfor %}
    </div>
</div>



{% endblock %}